spring:
  application:
    name: ms-customer-entity
  cloud:
    kubernetes:
      reload:
        enabled: true
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults:  false

databaseChangeLog:
  - includeAll:
      path: db/changelog/changes/

openapi:
  title: Customer Entity
  description: Customer Entity API
  version: 1.0.0
  security:
    scheme: client-credentials
    authorization-url: https://qwyck.eu.auth0.com/oauth/auth
    refresh-url: https://qwyck.eu.auth0.com/oauth/token
    token-url: https://qwyck.eu.auth0.com/oauth/token
    scopes: CUSTOMER_READ,CUSTOMER_WRITE